=== MediKnight/mediknight/Distribution/old/xsd/content.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Gerhard Vogel (Vogelfrei) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" elementFormDefault="qualified">
	<xsd:attributeGroup name="imageattributes">
		<xsd:attribute name="name" type="xsd:string"/>
		<xsd:attribute name="style" type="xsd:string"/>
		<xsd:attribute name="scale_width" type="xsd:string"/>
		<xsd:attribute name="scale_height" type="xsd:string"/>
	</xsd:attributeGroup>
	<xsd:attributeGroup name="textattributes">
		<xsd:attribute name="content" type="xsd:string"/>
		<xsd:attribute name="style" type="xsd:string"/>
	</xsd:attributeGroup>
	<xsd:attributeGroup name="tableattributes">
		<xsd:attribute name="colspan" type="xsd:byte"/>
		<xsd:attribute name="rowspan" type="xsd:byte"/>
		<xsd:attribute name="width" type="xsd:string"/>
		<xsd:attribute name="height" type="xsd:string"/>
		<xsd:attribute name="style" type="xsd:string"/>
		<xsd:attribute name="border" type="xsd:integer"/>
		<xsd:attribute name="cellpadding" type="xsd:string"/>
		<xsd:attribute name="cellspacing" type="xsd:string"/>
		<xsd:attribute name="splitting" type="xsd:string"/>
	</xsd:attributeGroup>
	<xsd:complexType name="imagedefinition">
		<xsd:attributeGroup ref="imageattributes"/>
	</xsd:complexType>
	<xsd:complexType name="textdefinition">
		<xsd:attributeGroup ref="textattributes"/>
	</xsd:complexType>
	<xsd:complexType name="tabledefinition">
		<xsd:attributeGroup ref="tableattributes"/>
	</xsd:complexType>
	<xsd:element name="specification" type="tabledefinition"/>
	<xsd:element name="image" type="imagedefinition"/>
	<xsd:element name="text" type="textdefinition"/>
	<xsd:element name="header">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="specification"/>
				<xsd:element ref="text" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="table" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="data">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="specification"/>
				<xsd:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="table" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="text" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="row">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="specification"/>
				<xsd:element ref="data" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="header" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="table">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="specification"/>
				<xsd:element ref="row" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="content">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element ref="image" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="text" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="table" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== MediKnight/mediknight/Distribution/old/xml/content.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Gerhard Vogel (Vogelfrei) -->
<content xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/content.xsd">
	<table>
		<specification width="100%"/>
		<row>
			<specification/>
			<data>
				<specification width="60%"/>
			</data>
			<data>
				<specification width="40%"/>
				$LOGO
			</data>
		</row>
		<row>
			<specification/>
			<data>
				<specification width="60%"/>
				<text content="${SENDER}" style="${FONT},8pt,underlined"/>
				<text content="${ADDRESS}" style="${FONT},11pt\n"/>
				<text content="&#160;" style="${FONT},11pt"/>
			</data>
			<data>
				<specification width="40%"/>
				<text content="&#160;" style="${FONT},11pt"/>
				<text content="&#160;" style="${FONT},11pt"/>
				<text content="Rechnung Nr.: ${ID}" style="${FONT},11pt"/>
				<text content="Datum: ${DATE}" style="${FONT},11pt"/>
			</data>
		</row>
	</table>


	<text content="&#160;" style="${FONT},11pt"/>
	<text content="&#160;" style="${FONT},11pt"/>
	<text content="&#160;" style="${FONT},11pt"/>
	<text content="${TEXT}" style="${FONT},11pt"/>

	<text content="&#160;" style="${FONT},11pt"/>
	$TABLE
	<text content="&#160;" style="${FONT},11pt"/>
	<table>
		<specification width="100%" cellpadding="4"/>
		<row>
			<specification border="64"/>
			<data>
				<specification width="66%"/>
			</data>
			<data>
				<specification width="19%"/>
				<text content="Gesamtbetrag:" style="${FONT},11pt,right"/>
			</data>
			<data>
				<specification width="15%"/>
				<text content="${TOTAL}" style="${FONT},11pt,right"/>
			</data>
		</row>
	</table>
	<text content="&#160;" style="${FONT},11pt"/>
	<text content="${CLOSING}" style="${FONT},11pt"/>
	<text content="&#160;" style="${FONT},11pt"/>
	<text content="&#160;" style="${FONT},11pt"/>
	$FINAL
</content>

=== MediKnight/mediknight/Distribution/xml/diagnosis.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Gerhard Vogel (Vogelfrei) -->
<content xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/content.xsd">

	<text content="${NAME}" style="${FONT},16pt,bold"/>
	<text content="&#160;" style="Times,11pt"/>

	<table>
		<specification width="100%"/>
		<row>
			<specification/>
		        <header>
				<specification width="100%"/>
				<text content="Dauerdiagnose:" style="${FONT},11pt,bold"/>
			</header>
		</row>
		<row>
			<specification/>
			<data>
				<specification width="100%"/>
				<text content="${DAUER}" style="${FONT},11pt"/>
			</data>
		</row>
	</table>
	<text content="&#160;" style="Times,11pt"/>
	<table>
	    <specification width="100%" border="128"/>
	    $for p in DIAGNOSEN {
		<row>
			<specification/>
		        <data>
				<specification width="100%" border="11"/>
				<text content="Tagesdiagnose vom $p.0" style="${FONT},11pt,bold"/>
				<text content="&#160;" style="Times,6pt"/>
			</data>
		</row>
		<row>
			<specification colspan="2"/>
			<data>
				<specification width="100%" border="14"/>
				<text content="$p.1" style="${FONT},11pt"/>
			</data>
		</row>
		<row>
			<specification colspan="2"/>
			<data>
				<specification width="100%"/>
				<text content="&#160;" style="Times,11pt"/>
			</data>
		</row>
	    }
	</table>
</content>

=== MediKnight/mediknight/Distribution/xml/content_medication.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XML Spy v3.5 NT (http://www.xmlspy.com) by Gerhard Vogel (Vogelfrei) -->
<content xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/content.xsd">
	<table>
		<specification width="100%"/>
		<row>
			<specification/>
			<data>
				<specification width="60%"/>
			</data>
			<data>
				<specification width="40%"/>
				$LOGO
			</data>
		</row>
		<row>
			<specification/>
			<data>
				<specification width="60%"/>
				<text content="${SENDER}" style="${FONT},8pt,underlined"/>
				<text content="${ADDRESS}" style="${FONT},11pt"/>
			</data>
			<data>
				<specification width="40%"/>
			</data>
		</row>
		<row>
			<specification/>
			<data>
				<specification width="60%"/>
			</data>
			<data>
				<specification width="40%"/>
				<text content="Datum: ${DATE}" style="${FONT},11pt"/>
			</data>
		</row>
	</table>
	<text content="&#160;" style="Times,11pt"/>
	<text content="&#160;" style="Times,11pt"/>
	<text content="Verordnung:" style="${FONT},11pt"/>
	<text content="&#160;" style="Times,11pt"/>
	<text content="&#160;" style="Times,11pt"/>
	<text content="${MEDICATION}" style="${FONT},11pt"/>
	<text content="&#160;" style="Times,11pt"/>
	<text content="&#160;" style="Times,11pt"/>
	$FINAL
</content>
